version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
cache:
  paths:
    - node_modules/**/*
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
